version: 0.0
os: linux
files:
  - source: Projects/eurekaServer/target/EurekaServer.jar
    destination: /tmp
hooks:
  ApplicationStart:
    - location: Projects/run.sh
      timeout: 300
      runas: ubuntu
