server:
  port: 3333   #default port where the service will be started
 
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:    
  application:
    name: add-payment-service   #current service name to be used by the eureka server
  datasource:
    url: jdbc:mysql://devops_db_1:3306/test_db?autoReconnect=true&useSSL=false
    username: dbuser
    password: dbuser
    driver-class-name: com.mysql.jdbc.Driver        
     
management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
 
logging:
  level:
    com.tcs.addPayment: DEBUG
    