	node  {

	mvnHome = tool 'maven_3.3.9'


	echo "PATH = ${PATH}"
	echo "M3_HOME = ${mvnHome}"
	env.PATH = "${mvnHome}/bin:${PATH}"


	stage('Checkout SCM') { checkout scm }

	stage('Build') {

		dir ('Projects/apiGateway') { sh "mvn clean install -Dmaven.test.skip=true " }
	}


	stage('Create Docker Image') {
		sh "cp Projects/apiGateway/target/*.jar Projects/apiGateway/dockerfile/"
		dir ('Projects/apiGateway/dockerfile') {
			def dicoveryApp = docker.build("int_region/api-gateway:${env.BUILD_ID}")
		}
	}
	stage ('Run Docker Image') {
		docker.image("int_region/api-gateway:${env.BUILD_ID}").run('-p 8084:8084 -h api-gateway --name api-gateway --network  devops_default --ip 172.18.0.10)
	}
}