node {

	mvnHome = tool 'maven_3.3.9'
	echo "PATH = ${PATH}"
	echo "M3_HOME = ${mvnHome}"
	env.PATH = "${mvnHome}/bin:${PATH}"

	stage('Build') {

		 build job: 'build_add_payment_pipeline' 
	}

	stage('Docker Image') {

		sh "cp Projects/addPayment/target/*.jar Projects/addPayment/dockerfile/"

		dir ('Projects/addPayment/dockerfile') {
			def addPaymentApp = docker.build("int_region/add-payment-service:${env.BUILD_ID}")
		}
	}
	stage ('Add Payment Run') {

		docker.image("int_region/add-payment-service:${env.BUILD_ID}").run('-p 3333:3333 -h addPayment --name addPayment --network  devops_default --dns=172.18.0.5')
		sh 'sleep 10'
	}

	stage('Unit Testing & Code Analysis') {

		dir ('Projects/addPayment') {
			withSonarQubeEnv('sonar_QB') { sh "mvn test sonar:sonar -Dsonar.login=sonar -Dsonar.password=sonar" }
			cucumber '**/target/*.json'
		}
	}
}