spring:
  application:
    name=API-Gateway
    
eureka:
  client:
     serviceUrl:
       defaultZone:http://discovery:8761/eureka/
server:
   port: 8084
   
security :
  basic:
     enable: false   
     
     
management:
   security:
      enabled: false
zuul:
  routes:
    addpayment:
      path: /sendPayment/**
      serviceId: add-payment-service
  host:
  	socket-timeout-millis=30000	  
    
    
ribbon:
  eureka:
    enabled: false      
