node {
	mvnHome = tool 'mvn_3.5.4'
	echo "PATH = ${PATH}"
	echo "M3_HOME = ${mvnHome}"
	env.PATH = "${mvnHome}/bin:${PATH}"



	stage('Checkout SCM') { checkout scm }

	stage('Build') {

		dir ('Projects/eft') { sh "mvn clean install -Dmaven.test.skip=true " }
	}

	stage('Create Docker Image') {

		sh "cp Projects/eft/target/*.jar Projects/eft/dockerfile/"
		dir ('Projects/eft/dockerfile') {
			def eftApp = docker.build("int_region/eft-service:${env.BUILD_ID}")
		}
	}


	stage ('Run Docker Image') {

		docker.image("int_region/eft-service:${env.BUILD_ID}").run('-p 3336:3336 -h eft --name eft --network  docknet --ip=172.18.0.7')
		sh 'sleep 10'
	}


}