node {
	mvnHome = tool 'maven_3.3.9'
	echo "PATH = ${PATH}"
	echo "M3_HOME = ${mvnHome}"
	env.PATH = "${mvnHome}/bin:${PATH}"



	stage('Checkout SCM') { checkout scm }

	stage('Build') {

		dir ('Projects/payment') { sh "mvn clean install -Dmaven.test.skip=true " }
	}

	stage('Create Docker Image') {

		sh "cp Projects/payment/target/*.jar Projects/payment/dockerfile/"
		dir ('Projects/payment/dockerfile') {
			def showPaymentApp = docker.build("int_region/payment-service:${env.BUILD_ID}")
		}
	}


	stage ('Run Docker Image') {

		docker.image("int_region/payment-service:${env.BUILD_ID}").run('-p 3334:3334 -h payment --name payment --network  docknet --ip=172.18.0.6')
		sh 'sleep 10'
	}

	stage('Integration Testing & Code Analysis') {
		dir ('Projects/payment') {
			withSonarQubeEnv('sonar_QB') { sh "mvn test sonar:sonar -Dsonar.login=sonar -Dsonar.password=sonar" }
			//generate cucumber reports
			cucumber '**/target/*.json'

		}
	}
}