node {
	mvnHome = tool 'mvn_3.5.4'
	echo "PATH = ${PATH}"
	echo "M3_HOME = ${mvnHome}"
	env.PATH = "${mvnHome}/bin:${PATH}"



	stage('Checkout SCM') { checkout scm }

	stage('Build') {

		dir ('Projects/card') { sh "mvn clean install -Dmaven.test.skip=true " }
	}

	stage('Create Docker Image') {

		sh "cp Projects/card/target/*.jar Projects/card/dockerfile/"
		dir ('Projects/card/dockerfile') {
			def cardApp = docker.build("int_region/card-service:${env.BUILD_ID}")
		}
	}


	stage ('Run Docker Image') {

		docker.image("int_region/card-service:${env.BUILD_ID}").run('-p 3337:3337 -h card --name card --network  docknet --ip=172.18.0.8')
		sh 'sleep 10'
	}
	stage('Integration Testing & Code Analysis') {

		dir ('Projects/addPayment') {
			withSonarQubeEnv('sonar_QB') { sh "mvn test sonar:sonar -Dsonar.login=sonar -Dsonar.password=sonar" }
			cucumber '**/target/*.json'
		}
	}

}