node {
	mvnHome = tool 'maven_3.3.9'
	echo "PATH = ${PATH}"
	echo "M3_HOME = ${mvnHome}"
	env.PATH = "${mvnHome}/bin:${PATH}"



	stage('Build') {
		build job: 'build_show_payment_pipeline' 
	}

	stage('Docker Image') {

		sh "cp Projects/showPayment/target/*.jar Projects/showPayment/dockerfile/"
		dir ('Projects/showPayment/dockerfile') {
			def showPaymentApp = docker.build("int_region/show-payment-service:${env.BUILD_ID}")
		}
	}


	stage ('Show Payment Run') {

		docker.image("int_region/show-payment-service:${env.BUILD_ID}").run('-p 3334:3334 -h showPayment --name showPayment --network  devops_default --dns=172.18.0.6')
		sh 'sleep 10'
	}

	stage('Unit Testing & Code Analysis') {
		dir ('Projects/showPayment') {
			withSonarQubeEnv('sonae_QB') { sh "mvn test sonar:sonar -Dsonar.login=sonar -Dsonar.password=sonar" }
			//generate cucumber reports
			cucumber '**/target/*.json'

		}
	}
}