pipeline {
	agent any
	tools{ maven 'mvn-3.3.9' }
	stages {
		stage ('Initialize') {
			steps { sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' }
		}
		stage('Checkout SCM') {
			steps { checkout scm }
		}

		stage('Build') {
			steps {
				script {

					dir ('Projects/showPayment') { sh "mvn clean install -Dmaven.test.skip=true " }
				}
			}
		}

		stage('Image') {
			steps {
				script {

					sh "cp Projects/showPayment/target/*.jar Projects/showPayment/dockerfile/"


					dir ('Projects/showPayment/dockerfile') {
						def showPaymentApp = docker.build("turja/show-payment-service:${env.BUILD_ID}")
					}
				}
			}
		}

		stage ('Show Payment Run') {
			steps {
				script {
					docker.image("turja/show-payment-service:${env.BUILD_ID}").run('-p 3334:3334 -h showPayment --name showPayment --network  devops_default --dns=172.18.0.6')
					sh 'sleep 10'
				}
			}
		}
	}
}

