	node  {
	stage ('Initialize') { sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' }
	stage('Checkout SCM') {checkout scm }

	stage('Build') {

		dir ('Projects/eurekaServer') { sh "mvn clean install -Dmaven.test.skip=true " }
	}
}

stage('Image') {

	script {
		sh "cp Projects/eurekaServer/target/*.jar Projects/eurekaServer/dockerfile/"


		dir ('Projects/eurekaServer/dockerfile') {
			def dicoveryApp = docker.build("turja/discovery-service:${env.BUILD_ID}")
		}
	}
}
stage ('Eureka Run') {

	script {
		docker.image("turja/discovery-service:${env.BUILD_ID}").run('-p 8761:8761 -h discovery --name discovery --network  devops_default --dns=172.18.0.4')
	}
}


