	node  {

	mvnHome = tool 'mvn_3.5.4'


	echo "PATH = ${PATH}"
	echo "M3_HOME = ${mvnHome}"
	env.PATH = "${mvnHome}/bin:${PATH}"


	stage('Checkout SCM') { checkout scm } 

	stage('Build') {

		dir ('Projects/eurekaServer') { sh "mvn clean install -Dmaven.test.skip=true " }
	}

}

