node {
	mvnHome = tool 'mvn_3.5.4'
	echo "PATH = ${PATH}"
	echo "M3_HOME = ${mvnHome}"
	env.PATH = "${mvnHome}/bin:${PATH}"

	stage('Checkout SCM') { checkout scm }
	stage('Build') {
		dir ('Projects/paymentwebApp') { sh "mvn clean install -Dmaven.test.skip=true " }
	}
	stage('Create Docker Image') {
		sh "cp Projects/paymentwebApp/target/*.jar Projects/paymentwebApp/dockerfile/"

		dir ('Projects/paymentwebApp/dockerfile') {
			def showPaymentApp = docker.build("int_region/payment-web-app:${env.BUILD_ID}")
		}
	}
	stage ('Run Docker Image') {
		docker.image("int_region/payment-web-app:${env.BUILD_ID}").run('-p 3340:3340 -h paymentWeb --name paymentWeb --network  docknet --ip=172.18.0.10')
	}

}



