pipeline {
	agent any
	tools{ maven 'mvn-3.3.9' }
	stages {
		stage ('Initialize') { steps { sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
			} }
		stage('Checkout SCM') { steps { checkout scm
			} }

		stage('Build') {
			steps {
				script {

					dir ('Projects/paymentwebApp') { sh "mvn clean install -Dmaven.test.skip=true " }
				}
			}
		}

		stage('Docker Image') {
			steps {
				script {

					sh "cp Projects/paymentwebApp/target/*.jar Projects/paymentwebApp/dockerfile/"

					dir ('Projects/paymentwebApp/dockerfile') {
						def showPaymentApp = docker.build("int_region/payment-web-app:${env.BUILD_ID}")
					}
				}
			}
		}

		stage ('Payment Web Run') {
			steps {
				script {
					docker.image("int_region/payment-web-app:${env.BUILD_ID}").run('-p 3335:3335 -h paymentWeb --name paymentWeb --network  devops_default --dns=172.18.0.7')
				}
			}
		}
		stage('QA Testing & Code Analysis') {
			steps {
				script {
					dir ('Projects/paymentwebApp') {
						withSonarQubeEnv('sonar_dev_QB') { sh "mvn test sonar:sonar -Dsonar.login=sonar -Dsonar.password=sonar" }
					}
				}
			}
			post {
				always {
					junit '**/target/surefire-reports/*.xml'
				}
			}
		}
	}
}

